services:
  postgres:
    image: postgres:13-alpine  # Можно указать нужную версию PostgreSQL
    container_name: my_postgres  # Удобное имя контейнера
    environment:
      - POSTGRES_USER=user      # Имя пользователя для доступа к БД
      - POSTGRES_PASSWORD=password  # Пароль для доступа к БД
      - POSTGRES_DB=AdaptaCore     # Имя создаваемой базы данных
    ports:
      - "5432:5432"  # Проброс порта для доступа извне
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Монтирование тома для хранения данных

volumes:
  postgres_data:  # Определение тома для персистентного хранения данных